version: '3.8'

services:
  postgres-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: juangmaulana
      POSTGRES_PASSWORD: SecretCAPS12
      POSTGRES_DB: biowatch
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  web-app:
    build: ./FE
    ports:
      - "3000:3000"
    depends_on:
      - postgres-db
    restart: always

  ai-service:
    build: ./AI
    ports:
      - "7860:7860"
    restart: always

volumes:
  pgdata: