version: '3.8'

services:
  postgres-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: juangmaulana
      POSTGRES_PASSWORD: SecretCAPS12
      POSTGRES_DB: biowatch
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  web-app:
    build: ./FE
    ports:
      - "3000:3000"
    depends_on:
      - postgres-db
    restart: always

  ai-service:
    build: ./AI
    ports:
      - "7860:7860"
    restart: always

  audit-service:
    build: ./audit-service
    ports:
      - "4001:4001"
    env_file:
      - ./audit-service/.env
    depends_on:
      - postgres-db
    restart: always

  redis:
    image: redis:7-alpine
    ports:
      - "127.0.0.1:6379:6379"
    restart: always

  auth-service:
    build: ./auth-service
    ports:
      - "4000:4000"
    env_file:
      - ./auth-service/.env
    depends_on:
      - postgres-db
      - redis
    restart: always

  upload-endpoint:
    build: ./upload-endpoint
    ports:
      - "4002:4002"
    env_file:
      - ./upload-endpoint/.env
    depends_on:
      - postgres-db
      - ai-service
    restart: always

volumes:
  pgdata:
