import { Plant } from "./model";

const now = new Date();

export const mockPlants: Plant[] = [
    {
        id: 1,
        commonName: "Red Maple",
        scientificName: "Acer rubrum",
        family: "Sapindaceae",
        genus: "Acer",
        botanicalDescription: "Deciduous tree, medium-sized, red flowers in spring, red fall foliage.",
        botanicalDescriptionEn: "Deciduous tree, medium-sized, red flowers in spring, red fall foliage.",
        botanicalDescriptionId: "",
        ecologicalInformation: "Supports a variety of pollinators and birds; common in wetland areas.",
        ecologicalInformationEn: "Supports a variety of pollinators and birds; common in wetland areas.",
        ecologicalInformationId: "",
        environmentalImpact: "Generally beneficial; can dominate small wetland areas if unchecked.",
        environmentalImpactEn: "Generally beneficial; can dominate small wetland areas if unchecked.",
        environmentalImpactId: "",
        imagePath: "/images/red-maple.jpg",
        createdAt: now,
        updatedAt: now,
    },
    {
        id: 2,
        commonName: "Kudzu",
        scientificName: "Pueraria montana",
        family: "Fabaceae",
        genus: "Pueraria",
        botanicalDescription: "Fast-growing vine, trifoliate leaves, purple flowers.",
        botanicalDescriptionEn: "Fast-growing vine, trifoliate leaves, purple flowers.",
        botanicalDescriptionId: "",
        ecologicalInformation: "Native to Asia, invasive in many regions, smothers trees and shrubs.",
        ecologicalInformationEn: "Native to Asia, invasive in many regions, smothers trees and shrubs.",
        ecologicalInformationId: "",
        environmentalImpact: "Highly invasive; disrupts native ecosystems.",
        environmentalImpactEn: "Highly invasive; disrupts native ecosystems.",
        environmentalImpactId: "",
        imagePath: "/images/kudzu.jpg",
        createdAt: now,
        updatedAt: now,
    },
    {
        id: 3,
        commonName: "Sugar Maple",
        scientificName: "Acer saccharum",
        family: "Sapindaceae",
        genus: "Acer",
        botanicalDescription: "Large deciduous tree with palmate leaves, known for sap production.",
        botanicalDescriptionEn: "Large deciduous tree with palmate leaves, known for sap production.",
        botanicalDescriptionId: "",
        ecologicalInformation: "Provides habitat for birds and insects, contributes to forest canopy.",
        ecologicalInformationEn: "Provides habitat for birds and insects, contributes to forest canopy.",
        ecologicalInformationId: "",
        environmentalImpact: "Generally neutral; used in forestry and landscaping.",
        environmentalImpactEn: "Generally neutral; used in forestry and landscaping.",
        environmentalImpactId: "",
        imagePath: "/images/sugar-maple.jpg",
        createdAt: now,
        updatedAt: now,
    },
    {
        id: 4,
        commonName: "Giant Hogweed",
        scientificName: "Heracleum mantegazzianum",
        family: "Apiaceae",
        genus: "Heracleum",
        botanicalDescription: "Tall herbaceous plant, white umbrella-shaped flowers, toxic sap.",
        botanicalDescriptionEn: "Tall herbaceous plant, white umbrella-shaped flowers, toxic sap.",
        botanicalDescriptionId: "",
        ecologicalInformation: "Spreads along rivers and disturbed lands; toxic to humans.",
        ecologicalInformationEn: "Spreads along rivers and disturbed lands; toxic to humans.",
        ecologicalInformationId: "",
        environmentalImpact: "Invasive; poses health risks and outcompetes native plants.",
        environmentalImpactEn: "Invasive; poses health risks and outcompetes native plants.",
        environmentalImpactId: "",
        imagePath: "/images/giant-hogweed.jpg",
        createdAt: now,
        updatedAt: now,
    },
    {
        id: 5,
        commonName: "White Oak",
        scientificName: "Quercus alba",
        family: "Fagaceae",
        genus: "Quercus",
        botanicalDescription: "Large deciduous tree with lobed leaves and white bark.",
        botanicalDescriptionEn: "Large deciduous tree with lobed leaves and white bark.",
        botanicalDescriptionId: "",
        ecologicalInformation: "Supports wildlife, provides acorns for food, forest-dominant species.",
        ecologicalInformationEn: "Supports wildlife, provides acorns for food, forest-dominant species.",
        ecologicalInformationId: "",
        environmentalImpact: "Beneficial; important for ecosystem stability.",
        environmentalImpactEn: "Beneficial; important for ecosystem stability.",
        environmentalImpactId: "",
        imagePath: "/images/white-oak.jpg",
        createdAt: now,
        updatedAt: now,
    },
    {
        id: 6,
        commonName: "Japanese Knotweed",
        scientificName: "Fallopia japonica",
        family: "Polygonaceae",
        genus: "Fallopia",
        botanicalDescription: "Perennial herb with bamboo-like stems, small white flowers.",
        botanicalDescriptionEn: "Perennial herb with bamboo-like stems, small white flowers.",
        botanicalDescriptionId: "",
        ecologicalInformation: "Introduced from Asia, grows along waterways, very resilient.",
        ecologicalInformationEn: "Introduced from Asia, grows along waterways, very resilient.",
        ecologicalInformationId: "",
        environmentalImpact: "Highly invasive; damages infrastructure and native habitats.",
        environmentalImpactEn: "Highly invasive; damages infrastructure and native habitats.",
        environmentalImpactId: "",
        imagePath: "/images/japanese-knotweed.jpg",
        createdAt: now,
        updatedAt: now,
    },
    {
        id: 7,
        commonName: "Eastern Redbud",
        scientificName: "Cercis canadensis",
        family: "Fabaceae",
        genus: "Cercis",
        botanicalDescription: "Small tree with heart-shaped leaves, pink flowers in early spring.",
        botanicalDescriptionEn: "Small tree with heart-shaped leaves, pink flowers in early spring.",
        botanicalDescriptionId: "",
        ecologicalInformation: "Supports pollinators; commonly planted as ornamental.",
        ecologicalInformationEn: "Supports pollinators; commonly planted as ornamental.",
        ecologicalInformationId: "",
        environmentalImpact: "Generally beneficial; non-invasive native species.",
        environmentalImpactEn: "Generally beneficial; non-invasive native species.",
        environmentalImpactId: "",
        imagePath: "/images/eastern-redbud.jpg",
        createdAt: now,
        updatedAt: now,
    },
    {
        id: 8,
        commonName: "Black Cherry",
        scientificName: "Prunus serotina",
        family: "Rosaceae",
        genus: "Prunus",
        botanicalDescription: "Medium to large tree, dark bark, white spring flowers, small edible fruits.",
        botanicalDescriptionEn: "Medium to large tree, dark bark, white spring flowers, small edible fruits.",
        botanicalDescriptionId: "",
        ecologicalInformation: "Provides food and habitat for wildlife; common in forests.",
        ecologicalInformationEn: "Provides food and habitat for wildlife; common in forests.",
        ecologicalInformationId: "",
        environmentalImpact: "Neutral; important native species.",
        environmentalImpactEn: "Neutral; important native species.",
        environmentalImpactId: "",
        imagePath: "/images/black-cherry.jpg",
        createdAt: now,
        updatedAt: now,
    },
    {
        id: 9,
        commonName: "Autumn Olive",
        scientificName: "Elaeagnus umbellata",
        family: "Elaeagnaceae",
        genus: "Elaeagnus",
        botanicalDescription: "Shrub with silver leaves and small yellow flowers, produces berries.",
        botanicalDescriptionEn: "Shrub with silver leaves and small yellow flowers, produces berries.",
        botanicalDescriptionId: "",
        ecologicalInformation: "Introduced species, fixes nitrogen, spreads aggressively.",
        ecologicalInformationEn: "Introduced species, fixes nitrogen, spreads aggressively.",
        ecologicalInformationId: "",
        environmentalImpact: "Invasive; can outcompete native shrubs.",
        environmentalImpactEn: "Invasive; can outcompete native shrubs.",
        environmentalImpactId: "",
        imagePath: "/images/autumn-olive.jpg",
        createdAt: now,
        updatedAt: now,
    },
    {
        id: 10,
        commonName: "Sugarcane",
        scientificName: "Saccharum officinarum",
        family: "Poaceae",
        genus: "Saccharum",
        botanicalDescription: "Tall perennial grass with jointed stems, grows in tropical regions.",
        botanicalDescriptionEn: "Tall perennial grass with jointed stems, grows in tropical regions.",
        botanicalDescriptionId: "",
        ecologicalInformation: "Cultivated for sugar production, minimal native ecological role.",
        ecologicalInformationEn: "Cultivated for sugar production, minimal native ecological role.",
        ecologicalInformationId: "",
        environmentalImpact: "Generally neutral; mostly agricultural use.",
        environmentalImpactEn: "Generally neutral; mostly agricultural use.",
        environmentalImpactId: "",
        imagePath: "/images/sugarcane.jpg",
        createdAt: now,
        updatedAt: now,
    }
];