import { Plant } from "./schema";

export const mockPlants: Plant[] = [
  {
    id: 1,
    commonName: "Red Maple",
    scientificName: "Acer rubrum L.",
    family: "Sapindaceae",
    genus: "Acer",
    botanicalDescription: "Deciduous tree, medium-sized, red flowers in spring, red fall foliage.",
    ecologicalInformation: "Supports a variety of pollinators and birds; common in wetland areas.",
    environmentalImpact: "Generally beneficial; can dominate small wetland areas if unchecked.",
    referenceImagePath: "/images/red-maple.jpg",
  },
  {
    id: 2,
    commonName: "Kudzu",
    scientificName: "Pueraria montana (Lour.) Merr.",
    family: "Fabaceae",
    genus: "Pueraria",
    botanicalDescription: "Fast-growing vine, trifoliate leaves, purple flowers.",
    ecologicalInformation: "Native to Asia, invasive in many regions, smothers trees and shrubs.",
    environmentalImpact: "Highly invasive; disrupts native ecosystems.",
    referenceImagePath: "/images/kudzu.jpg",
  },
  {
    id: 3,
    commonName: "Sugar Maple",
    scientificName: "Acer saccharum Marshall",
    family: "Sapindaceae",
    genus: "Acer",
    botanicalDescription: "Large deciduous tree with palmate leaves, known for sap production.",
    ecologicalInformation: "Provides habitat for birds and insects, contributes to forest canopy.",
    environmentalImpact: "Generally neutral; used in forestry and landscaping.",
    referenceImagePath: "/images/sugar-maple.jpg",
  },
  {
    id: 4,
    commonName: "Giant Hogweed",
    scientificName: "Heracleum mantegazzianum Sommier & Levier",
    family: "Apiaceae",
    genus: "Heracleum",
    botanicalDescription: "Tall herbaceous plant, white umbrella-shaped flowers, toxic sap.",
    ecologicalInformation: "Spreads along rivers and disturbed lands; toxic to humans.",
    environmentalImpact: "Invasive; poses health risks and outcompetes native plants.",
    referenceImagePath: "/images/giant-hogweed.jpg",
  },
  {
    id: 5,
    commonName: "White Oak",
    scientificName: "Quercus alba L.",
    family: "Fagaceae",
    genus: "Quercus",
    botanicalDescription: "Large deciduous tree with lobed leaves and white bark.",
    ecologicalInformation: "Supports wildlife, provides acorns for food, forest-dominant species.",
    environmentalImpact: "Beneficial; important for ecosystem stability.",
    referenceImagePath: "/images/white-oak.jpg",
  },
  {
    id: 6,
    commonName: "Japanese Knotweed",
    scientificName: "Fallopia japonica (Houtt.) Ronse Decr.",
    family: "Polygonaceae",
    genus: "Fallopia",
    botanicalDescription: "Perennial herb with bamboo-like stems, small white flowers.",
    ecologicalInformation: "Introduced from Asia, grows along waterways, very resilient.",
    environmentalImpact: "Highly invasive; damages infrastructure and native habitats.",
    referenceImagePath: "/images/japanese-knotweed.jpg",
  },
  {
    id: 7,
    commonName: "Eastern Redbud",
    scientificName: "Cercis canadensis L.",
    family: "Fabaceae",
    genus: "Cercis",
    botanicalDescription: "Small tree with heart-shaped leaves, pink flowers in early spring.",
    ecologicalInformation: "Supports pollinators; commonly planted as ornamental.",
    environmentalImpact: "Generally beneficial; non-invasive native species.",
    referenceImagePath: "/images/eastern-redbud.jpg",
  },
  {
    id: 8,
    commonName: "Black Cherry",
    scientificName: "Prunus serotina Ehrh.",
    family: "Rosaceae",
    genus: "Prunus",
    botanicalDescription: "Medium to large tree, dark bark, white spring flowers, small edible fruits.",
    ecologicalInformation: "Provides food and habitat for wildlife; common in forests.",
    environmentalImpact: "Neutral; important native species.",
    referenceImagePath: "/images/black-cherry.jpg",
  },
  {
    id: 9,
    commonName: "Autumn Olive",
    scientificName: "Elaeagnus umbellata Thunb.",
    family: "Elaeagnaceae",
    genus: "Elaeagnus",
    botanicalDescription: "Shrub with silver leaves and small yellow flowers, produces berries.",
    ecologicalInformation: "Introduced species, fixes nitrogen, spreads aggressively.",
    environmentalImpact: "Invasive; can outcompete native shrubs.",
    referenceImagePath: "/images/autumn-olive.jpg",
  },
  {
    id: 10,
    commonName: "Sugarcane",
    scientificName: "Saccharum officinarum L.",
    family: "Poaceae",
    genus: "Saccharum",
    botanicalDescription: "Tall perennial grass with jointed stems, grows in tropical regions.",
    ecologicalInformation: "Cultivated for sugar production, minimal native ecological role.",
    environmentalImpact: "Generally neutral; mostly agricultural use.",
    referenceImagePath: "/images/sugarcane.jpg",
  },
];
